language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - extra-android-m2repository
    - extra-android-support
    - android-28

sudo: required

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: MVP
      script: 
        - cd sampleapp
        - ./gradlew mvp:clean mvp:build mvp:ktlint

    - stage: MVVM
      script: 
        - cd sampleapp
        - ./gradlew mvvm:clean mvvm:build mvvm:ktlint

    - stage: MVI
      script: 
        - cd sampleapp
        - ./gradlew mvi:clean mvi:build mvi:ktlint