language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - extra-android-m2repository
    - extra-android-support
    - android-28

sudo: required

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: buildMVP
      script: 
        - cd sampleapp
        - ./gradlew mvp:clean mvp:build -x test

    - stage: buildMVVM
      script: 
        - cd sampleapp
        - ./gradlew mvvm:clean mvvm:build -x test

    - stage: buildMVI
      script: 
        - cd sampleapp
        - ./gradlew mvi:clean mvi:build -x test

    - stage: test
      script: 
        - cd sampleapp
        - ./gradlew test